#!/bin/bash

update_dynamic_seedbox() {
    echo "Updating Dynamic Seedbox MAM_ID=$MAM_ID"
    curl -s -b "mam_id=$MAM_ID" -o /tmp/myanonamouse-dynamicSeedbox-result.txt \
        https://t.myanonamouse.net/json/dynamicSeedbox.php 2>/dev/null 2>&1
    echo $(cat /tmp/myanonamouse-dynamicSeedbox-result.txt)

    sleep $RECHECK_TIME

    update_dynamic_seedbox
}

sleep 30
update_dynamic_seedbox